name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install make
        run: |
          sudo apt-get update
          sudo apt-get -y install make

      - name: Create .env
        run: cp sample.env .env

      - name: Run Docker Compose
        run: make run

      - name: Validate composer.json
        run: |
          make composerdump
          make composervalidate
