name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create .env
        run: cp sample.env .env

      - name: Run Docker Compose
        run: docker compose up -d --build

      - name: Validate composer.json
        run: |
          docker exec -it lamp-php83 bash composer dump-autoload
          docker exec -it lamp-php83 bash validate --strict
